// <auto-generated />
using System;
using LoyaltyCouponsSystem.DAL.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoyaltyCouponsSystem.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250121130539_EditPermission")]
    partial class EditPermission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CouponRepresentative", b =>
                {
                    b.Property<string>("CouponsCouponeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RepresentativesApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CouponsCouponeId", "RepresentativesApplicationUserId");

                    b.HasIndex("RepresentativesApplicationUserId");

                    b.ToTable("CouponRepresentative");
                });

            modelBuilder.Entity("CouponStoreKeeper", b =>
                {
                    b.Property<string>("CouponsCouponeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StoreKeepersStoreKeeperID")
                        .HasColumnType("int");

                    b.HasKey("CouponsCouponeId", "StoreKeepersStoreKeeperID");

                    b.HasIndex("StoreKeepersStoreKeeperID");

                    b.ToTable("CouponStoreKeeper");
                });

            modelBuilder.Entity("CouponTechnician", b =>
                {
                    b.Property<string>("CouponsCouponeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TechniciansTechnicianID")
                        .HasColumnType("int");

                    b.HasKey("CouponsCouponeId", "TechniciansTechnicianID");

                    b.HasIndex("TechniciansTechnicianID");

                    b.ToTable("CouponTechnician");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.DB.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governorate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagepath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OptionalPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NationalID")
                        .IsUnique()
                        .HasFilter("[NationalID] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.HasIndex("TechnicianId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Admin", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ApplicationUserId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GovernateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovernateId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.AuditLog", b =>
                {
                    b.Property<int>("AuditLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AdminApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AdminID")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("AuditLogID");

                    b.HasIndex("AdminApplicationUserId");

                    b.HasIndex("EmployeeID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Coupon", b =>
                {
                    b.Property<string>("CouponeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<long>("NumInYear")
                        .HasColumnType("bigint");

                    b.Property<int?>("RepresentativeId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StorekeeperID")
                        .HasColumnType("int");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfCoupone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("CouponeId");

                    b.HasIndex("AreaId");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.HasIndex("TechnicianId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Distributor", b =>
                {
                    b.Property<int>("DistributorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributorID"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Governate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber1")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DistributorID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CustomerID");

                    b.HasIndex("PhoneNumber1")
                        .IsUnique();

                    b.ToTable("Distributors");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.DistributorCustomer", b =>
                {
                    b.Property<int>("DistributorID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.HasKey("DistributorID", "CustomerID");

                    b.HasIndex("CustomerID");

                    b.ToTable("DistributorCustomer");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.GlobalCounter", b =>
                {
                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Year"));

                    b.Property<long>("MaXNumberInYear")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxSerialNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("YearNotId")
                        .HasColumnType("int");

                    b.HasKey("Year");

                    b.ToTable("GlobalCounters");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Governorates");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Permission.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manage Customers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manage Distributors"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Manage Technicias"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Manage Users"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Generate QR Codes"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Exchange Permissions"
                        });
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Permission.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.QRCodeTransactionGenerated", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosureDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneratedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GovernorateID")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfCoupones")
                        .HasColumnType("int");

                    b.Property<int?>("RepresentativeId")
                        .HasColumnType("int");

                    b.Property<int?>("StorekeeperID")
                        .HasColumnType("int");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("ToSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfCoupone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AreaId");

                    b.HasIndex("GovernorateID");

                    b.ToTable("qRCodeTransactionGenerateds");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.QRScanLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumberOfScans")
                        .HasColumnType("int");

                    b.Property<string>("QR_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScanTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QRScanLogs");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Representative", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionalPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QRCodeTransactionGeneratedID")
                        .HasColumnType("int");

                    b.HasKey("ApplicationUserId");

                    b.HasIndex("QRCodeTransactionGeneratedID");

                    b.ToTable("Representatives");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.StoreKeeper", b =>
                {
                    b.Property<int>("StoreKeeperID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreKeeperID"));

                    b.Property<string>("ContactDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAttribute")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("QRCodeTransactionGeneratedID")
                        .HasColumnType("int");

                    b.HasKey("StoreKeeperID");

                    b.HasIndex("QRCodeTransactionGeneratedID");

                    b.ToTable("StoreKeepers");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Technician", b =>
                {
                    b.Property<int>("TechnicianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechnicianID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber1")
                        .HasColumnType("int");

                    b.Property<int?>("PhoneNumber2")
                        .HasColumnType("int");

                    b.Property<int?>("PhoneNumber3")
                        .HasColumnType("int");

                    b.Property<int?>("QRCodeTransactionGeneratedID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TechnicianID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PhoneNumber1")
                        .IsUnique();

                    b.HasIndex("QRCodeTransactionGeneratedID");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouponSort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouponType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("ExchangePermission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PurchaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SequenceEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("SequenceStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechnicianID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransactionID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("TechnicianID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CouponRepresentative", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Coupon", null)
                        .WithMany()
                        .HasForeignKey("CouponsCouponeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Representative", null)
                        .WithMany()
                        .HasForeignKey("RepresentativesApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CouponStoreKeeper", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Coupon", null)
                        .WithMany()
                        .HasForeignKey("CouponsCouponeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.StoreKeeper", null)
                        .WithMany()
                        .HasForeignKey("StoreKeepersStoreKeeperID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CouponTechnician", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Coupon", null)
                        .WithMany()
                        .HasForeignKey("CouponsCouponeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Technician", null)
                        .WithMany()
                        .HasForeignKey("TechniciansTechnicianID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.DB.ApplicationUser", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Technician", "Technician")
                        .WithMany("Users")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Admin", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.DB.ApplicationUser", "ApplicationUser")
                        .WithOne("Admin")
                        .HasForeignKey("LoyaltyCouponsSystem.DAL.Entity.Admin", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Area", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Governorate", "Governorate")
                        .WithMany("Areas")
                        .HasForeignKey("GovernateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.AuditLog", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Admin", "Admin")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AdminApplicationUserId");

                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Employee", "Employee")
                        .WithMany("AuditLogs")
                        .HasForeignKey("EmployeeID");

                    b.Navigation("Admin");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Coupon", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Area", "Areas")
                        .WithMany("CouponList")
                        .HasForeignKey("AreaId");

                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Governorate", "Governorates")
                        .WithMany("CouponList")
                        .HasForeignKey("GovernorateId");

                    b.Navigation("Areas");

                    b.Navigation("Governorates");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Customer", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Technician", "Technician")
                        .WithMany("Customers")
                        .HasForeignKey("TechnicianId");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Distributor", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Customer", null)
                        .WithMany("Distributors")
                        .HasForeignKey("CustomerID");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.DistributorCustomer", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Customer", "Customer")
                        .WithMany("DistributorCustomers")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Distributor", "Distributor")
                        .WithMany("DistributorCustomers")
                        .HasForeignKey("DistributorID");

                    b.Navigation("Customer");

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Permission.RolePermission", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Permission.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.QRCodeTransactionGenerated", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Area", "Areas")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Governorate", "Governorates")
                        .WithMany()
                        .HasForeignKey("GovernorateID");

                    b.Navigation("Areas");

                    b.Navigation("Governorates");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Representative", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.DB.ApplicationUser", "ApplicationUser")
                        .WithOne("Representative")
                        .HasForeignKey("LoyaltyCouponsSystem.DAL.Entity.Representative", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.QRCodeTransactionGenerated", null)
                        .WithMany("Representatives")
                        .HasForeignKey("QRCodeTransactionGeneratedID");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.StoreKeeper", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.QRCodeTransactionGenerated", null)
                        .WithMany("StoreKeepers")
                        .HasForeignKey("QRCodeTransactionGeneratedID");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Technician", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.QRCodeTransactionGenerated", null)
                        .WithMany("Technicians")
                        .HasForeignKey("QRCodeTransactionGeneratedID");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Transaction", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoyaltyCouponsSystem.DAL.Entity.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.DB.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.DB.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoyaltyCouponsSystem.DAL.DB.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LoyaltyCouponsSystem.DAL.DB.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.DB.ApplicationUser", b =>
                {
                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("Representative")
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Admin", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Area", b =>
                {
                    b.Navigation("CouponList");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Customer", b =>
                {
                    b.Navigation("DistributorCustomers");

                    b.Navigation("Distributors");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Distributor", b =>
                {
                    b.Navigation("DistributorCustomers");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Employee", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Governorate", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("CouponList");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Permission.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.QRCodeTransactionGenerated", b =>
                {
                    b.Navigation("Representatives");

                    b.Navigation("StoreKeepers");

                    b.Navigation("Technicians");
                });

            modelBuilder.Entity("LoyaltyCouponsSystem.DAL.Entity.Technician", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
